services:
  mysql:
    image: mysql:9-oracle
    volumes:
      - ./db/data_dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=clave123
      - MYSQL_HOST=mysql
    ports:
      - '3308:3306'
  api-dev:
    image: node:22-alpine3.19
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - '3000:3000'
    command: 'yarn start:dev'
